let employees=[
{"eid":1,"ename":"Adora","gender":"Female"},
{"eid":2,"ename":"Jamil","gender":"Male"},
{"eid":3,"ename":"Rowen","gender":"Male"},
{"eid":4,"ename":"Lauryn","gender":"Female"},
{"eid":5,"ename":"Manon","gender":"Female"},
{"eid":6,"ename":"Rodd","gender":"Male"},
{"eid":7,"ename":"Ronny","gender":"Genderfluid"},
{"eid":8,"ename":"Liane","gender":"Female"},
{"eid":9,"ename":"Haven","gender":"Male"},
{"eid":10,"ename":"Karia","gender":"Female"},
{"eid":11,"ename":"Kinny","gender":"Male"},
{"eid":12,"ename":"Mellisa","gender":"Female"},
{"eid":13,"ename":"Ashil","gender":"Female"},
{"eid":14,"ename":"Rad","gender":"Male"},
{"eid":15,"ename":"Hedi","gender":"Female"},
{"eid":16,"ename":"Anjanette","gender":"Female"},
{"eid":17,"ename":"Paddie","gender":"Male"},
{"eid":18,"ename":"Lissie","gender":"Female"},
{"eid":19,"ename":"Junie","gender":"Female"},
{"eid":20,"ename":"Ilaire","gender":"Male"},
{"eid":21,"ename":"Brnaby","gender":"Male"},
{"eid":22,"ename":"Bordie","gender":"Male"},
{"eid":23,"ename":"Audrie","gender":"Female"},
{"eid":24,"ename":"Marylynne","gender":"Agender"},
{"eid":25,"ename":"Thurstan","gender":"Male"},
{"eid":26,"ename":"Carrol","gender":"Male"},
{"eid":27,"ename":"Olin","gender":"Male"},
{"eid":28,"ename":"Gae","gender":"Female"},
{"eid":29,"ename":"Fax","gender":"Male"},
{"eid":30,"ename":"Dionne","gender":"Female"},
{"eid":31,"ename":"Darill","gender":"Male"},
{"eid":32,"ename":"Hamid","gender":"Male"},
{"eid":33,"ename":"Britt","gender":"Genderqueer"},
{"eid":34,"ename":"Cleo","gender":"Female"},
{"eid":35,"ename":"Arvie","gender":"Male"},
{"eid":36,"ename":"Bernhard","gender":"Male"},
{"eid":37,"ename":"Ford","gender":"Male"},
{"eid":38,"ename":"Arnaldo","gender":"Male"},
{"eid":39,"ename":"Bonnie","gender":"Female"},
{"eid":40,"ename":"Fulvia","gender":"Female"},
{"eid":41,"ename":"Padraig","gender":"Male"},
{"eid":42,"ename":"Magdalena","gender":"Female"},
{"eid":43,"ename":"Ardis","gender":"Female"},
{"eid":44,"ename":"Westleigh","gender":"Genderqueer"},
{"eid":45,"ename":"Aloin","gender":"Male"},
{"eid":46,"ename":"Tanner","gender":"Male"},
{"eid":47,"ename":"Pietrek","gender":"Male"},
{"eid":48,"ename":"Hattie","gender":"Agender"},
{"eid":49,"ename":"Titos","gender":"Male"},
{"eid":50,"ename":"Sibelle","gender":"Female"},
{"eid":51,"ename":"Cornela","gender":"Female"},
{"eid":52,"ename":"Inger","gender":"Non-binary"},
{"eid":53,"ename":"Paige","gender":"Female"},
{"eid":54,"ename":"Waneta","gender":"Female"},
{"eid":55,"ename":"Basil","gender":"Male"},
{"eid":56,"ename":"Fredra","gender":"Female"},
{"eid":57,"ename":"Dalston","gender":"Male"},
{"eid":58,"ename":"Caddric","gender":"Male"},
{"eid":59,"ename":"Moise","gender":"Male"},
{"eid":60,"ename":"Rouvin","gender":"Male"},
{"eid":61,"ename":"Gabbie","gender":"Male"},
{"eid":62,"ename":"Kort","gender":"Male"},
{"eid":63,"ename":"Korey","gender":"Male"},
{"eid":64,"ename":"Domenico","gender":"Male"},
{"eid":65,"ename":"Kalil","gender":"Male"},
{"eid":66,"ename":"Valentina","gender":"Female"},
{"eid":67,"ename":"Hammad","gender":"Male"},
{"eid":68,"ename":"Alejandro","gender":"Male"},
{"eid":69,"ename":"Cele","gender":"Female"},
{"eid":70,"ename":"Connor","gender":"Male"},
{"eid":71,"ename":"Theresina","gender":"Female"},
{"eid":72,"ename":"Wilie","gender":"Female"},
{"eid":73,"ename":"Em","gender":"Male"},
{"eid":74,"ename":"Corie","gender":"Female"},
{"eid":75,"ename":"Emilie","gender":"Female"},
{"eid":76,"ename":"Gayle","gender":"Bigender"},
{"eid":77,"ename":"Aluino","gender":"Male"},
{"eid":78,"ename":"Gearalt","gender":"Male"},
{"eid":79,"ename":"Tanney","gender":"Male"},
{"eid":80,"ename":"Siffre","gender":"Male"},
{"eid":81,"ename":"Lorry","gender":"Male"},
{"eid":82,"ename":"Lianne","gender":"Female"},
{"eid":83,"ename":"Lyda","gender":"Female"},
{"eid":84,"ename":"Giustina","gender":"Female"},
{"eid":85,"ename":"Viole","gender":"Female"},
{"eid":86,"ename":"Burty","gender":"Male"},
{"eid":87,"ename":"Jedidiah","gender":"Non-binary"},
{"eid":88,"ename":"Neely","gender":"Agender"},
{"eid":89,"ename":"Justinn","gender":"Female"},
{"eid":90,"ename":"Barde","gender":"Male"},
{"eid":91,"ename":"Penelopa","gender":"Female"},
{"eid":92,"ename":"Christophe","gender":"Male"},
{"eid":93,"ename":"Essie","gender":"Genderqueer"},
{"eid":94,"ename":"Halimeda","gender":"Female"},
{"eid":95,"ename":"Francyne","gender":"Female"},
{"eid":96,"ename":"Devlin","gender":"Male"},
{"eid":97,"ename":"Paige","gender":"Male"},
{"eid":98,"ename":"Orson","gender":"Male"},
{"eid":99,"ename":"Kerry","gender":"Female"},
{"eid":100,"ename":"Gram","gender":"Male"}]

let maleCount = 0;
let femaleCount = 0;

for (let emp of employees) {
    if (emp.gender === "Male") {
        maleCount++;
    } else if (emp.gender === "Female") {
        femaleCount++;
    }
}

console.log("No of Males:", maleCount);
console.log("No of Females:", femaleCount);